baseURL = "https://aigarsreiters.tech/blog/"
canonifyURLs = true
languageCode = "en-us"
title = "Aigars Rambles Tech"
theme = "casper3"
publishDir="straygar.github.io/blog/"
sectionPagesMenu = "main"

[params]
  description = "We all start somewhere"
  github = 'https://github.com/straygar/'

[menu]
[[menu.main]]
identifier = "about"
name = "About Me"
title = "About Me"
url = "https://aigarsreiters.tech/"
