baseURL = "https://aigarsreiters.tech/blog/"
canonifyURLs = true
languageCode = "en-us"
title = "Tech Blog"
theme = "casper3"
publishDir="straygar.github.io/blog/"
sectionPagesMenu = "main"

[menu]
[[menu.main]]
identifier = "about"
name = "About Me"
title = "About Me"
url = "https://aigarsreiters.tech/"
